/**
 * POST /api/invites       — attorney creates invite for a founder
 * GET  /api/invites/[token] — validate and consume an invite token
 */

import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { sendInviteEmail } from "@/lib/email/resend";
import { NextResponse } from "next/server";

export async function POST(request: Request) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { data: profile } = await supabase
    .from("users")
    .select("role, display_name, email")
    .eq("id", user.id)
    .single();

  if (profile?.role !== "attorney") {
    return NextResponse.json({ error: "Only attorneys can send invites" }, { status: 403 });
  }

  let body: { client_email: string };
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid request body" }, { status: 400 });
  }

  const { client_email } = body;
  if (!client_email?.includes("@")) {
    return NextResponse.json({ error: "Invalid email address" }, { status: 400 });
  }

  const admin = createAdminClient();

  // Create invite record (token auto-generated by DB default)
  const { data: invite, error: insertError } = await admin
    .from("invites")
    .insert({
      attorney_id: user.id,
      client_email: client_email.toLowerCase().trim(),
    })
    .select()
    .single();

  if (insertError) {
    return NextResponse.json({ error: "Failed to create invite" }, { status: 500 });
  }

  // Send invite email (fire and forget — invite is created regardless)
  const attorneyName = profile.display_name || profile.email;
  sendInviteEmail({
    to: client_email,
    attorneyName,
    token: invite.token,
  }).catch(() => {}); // Email failure logged but doesn't fail the request

  // Log notification
  await admin
    .from("notifications")
    .insert({
      user_id: user.id,
      event_type: "invite",
      serial_number: null,
    })
    .throwOnError();

  return NextResponse.json({ ok: true, token: invite.token }, { status: 201 });
}
